name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ACPI
        shell: bash
        run: |
          sudo apt install -y libacpi-dev libacpi0
      - name: Build
        shell: bash
        run: |
          make clean
          make all
